[build]
  command   = "npm run setup && npm run build"
  functions = "out_functions"
  publish   = "out_publish"

[[redirects]]
  from="/api/*"
  status = 200
  force = true
  conditions = {Role = ["user"]}

[[redirects]]
  from="/api-preview/states/daily"
  to="http://internalapi.covidtracking.com/api/v1/public/states/daily"
  status=200


[[redirects]]
  from="/public-api/*"
  to="https://api.covidtracking.com/:splat"
  status=200