[build]
  command   = "npm run setup && npm run build"
  functions = "out_functions"
  publish   = "out_publish"

[[redirects]]
  from="/state/*"
  status = 200
  force = true
  conditions = {Role = ["user"]}
